### ISSUE TITLE
Unsunk ship issues

### ISSUE THREAD

**Issue by mrdomino** [urbit/arvo#1168]
I recently restarted a couple of my ships with new keys. (I had to cycle the keys a couple times due to some combination of UI issues and confusion.) They seem able to say `|hi` to ~zod, but they aren't getting any talk messages from anyone. Also (this may be unrelated), they both seem to have failed to generate https certificates this time around, and seemed to encounter 504 errors like mentioned in #1103. Curious what's going on here and if there's anything to be done short of waiting for the next breach.

**Comment by joemfb** [comment]
@mrdomino, sorry for the delay. I suspect that you cycled your keys using bridge, which currently just supports "continuous" key cycling -- ie, normal key rotation, not an individual breach. The contracts support individual breaches, but our tooling currently requires you to go off the beaten path to create these transactions. More support is coming soon: urbit/bridge#130.

Note that Arvo supports individual breaches insofar as ames will reset sequence numbers, but there are some known issues with other vanes and the overall process is still fragile. Work is ongoing here is well, some is at urbit/arvo#1169. You may also need to (temporarily) configure your ships to get Azimuth events directly from an ethereum node in order to get them out of their disconnected state. The details therein exceed my knowledge or experience.

/cc @Fang-

**Comment by mrdomino** [comment]
You are correct, I cycled using bridge and just naively assumed that that
was doing the breach thing.

In that case, I'm surprised that I'm getting anything at all back from ~zod
on the new piers.

**Comment by Fang-** [comment]
Hey, hey! Hot new Bridge with "personal breach" support, fresh from the oven. [Get it here!](https://github.com/urbit/bridge/releases/latest)

**Comment by mrdomino** [comment]
I'm willing to believe that this just works now, aside from the various state issues.

Reported #1173 for the acme issues.

**Comment by mrdomino** [comment]
(Also, thanks for the help!
