### ISSUE TITLE
~dopzod/urbit-help Incommunicado

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/arvo#1209]
I will subscribe to ~dopzod/urbit-help via the client, but the past conversations won't scroll. I'll see the chat show up in Landscape, and click the conversation with nothing there.

I was able to see everything yesterday and several days previously. At that time I could see messages around 8am Central, and then nothing (even if I dot posted). Then, the next day all the messages would flood in (including my dot post) and then it would go silent again.

Shut down the planet, restarted it, and then all my villages, inboxes, etc are not showing up in Landscape.

**Comment by custom-jonathan** [comment]
I think I somehow installed urbit in two locations on my droplet. I closed the screen, and when I started my ship back up I didn't navigate to the correct location. This would explain why nothing I'd done in my ship was showing up; I think I was seeing a ghost version or something? I shut everything down, then followed the original walkthrough, and when I changed the directory before restarting the point everything seemed to work as it had been.

**Comment by Fang-** [comment]
Your issue with ~dopzod/urbit-help might just be ~dopzod falling asleep. Something buggy about connectivity right now, where ~dopzod occasionally just stops sending updates to people. I try to kick it awake when I can, but unfortunately can't be on top of that 24/7.

Closing this as both not-really-an-issue and fixed in new ames, which is (slowly but surely) on its way.
