### ISSUE TITLE
Syntax proposal: a~foo for |*(_[b=+<:foo c=+<:a:foo] (~(a foo b) c))

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#16]
My crusade against parens continues: `(gas~in a b)` is much cleaner than `(~(gas in a) b)`, not speaking of `:(uni~by a b c d)` or `(roll `(list (set))`foo int~in)`

The expansion could be better, but the purpose is hopefully clear.

**Comment by juped** [comment]
I kinda wish we had a better syntax for ~(. a b), actually

**Comment by ohAitch** [comment]
In what context, vang? I suppose (put:in~a b) would also be compact, but
it's less readable and doesn't have the same "a method call is just a
function whose first argument is Self" reduction.

**Comment by jtobin** [comment]
Closing this one as it hasn't attracted any attention in over three years and I don't see it going anywhere as-is.

Just for the sake of tangential and (hopefully) interesting meta-level conversation: I think a proposal like this is *best* made via a PR with an implementation attached, e.g. #1190, which can then be evaluated immediately in terms of merging or not merging the thing, instead of deciding "should we do this thing or should we not do this thing."

Making proposals in issues (like this one) or via mailing list discussions is also great and perfectly acceptable, of course.  That's the superior route for larger/more contentious changes that can't necessarily just be whipped up and proposed in a PR.
