### ISSUE TITLE
colored output requirements

### ISSUE THREAD

**Issue by joemfb** [urbit/arvo#212]
continuing the conversation from #203 ...

first, some molds:

```
++  kulr  ?($~ $r $g $b $c $m $y $k $w)                 ::  color or default
++  decr  ?($~ $bl $br $un)                             ::  decor or default
++  styl  (trel kulr decr tape)                         ::  inline text
```

These seem to fall naturally out of basic terminal color/style support (and the relevant ANSI codes...). A color is one of R/G/B, C/M/Y/K, white, or null. A text decoration is `blink`, `bright`, `underscore`, or null. And a piece of styled, inline text is a triple of color, decoration, and the text itself. A line of output is therefore `(list styl)`.

*(I'm making the assumption that background colors, hidden text, reversed text, etc. are out of scope.)*

Wrapping this up as a `++sole-effect` is pretty straightforward; something like: `{$klr p/(list styl)}`. However, I can't shake the feeling that colored output should be available at a lower level ...

The obvious use-cases are generators and unlinked apps that produce output in response to pokes (as `:hood` does with `|sync`, `|merge`, etc.). I know the long-term plan is for `syslog`-style output to be sent to a `:talk` channel, but, even then, `++sole-effect` doesn't quite feel natural...

If this were to be added to `++tank`, I'd propose something like `{$vein p/styl}`, and maybe even `{$leaf p/?(tape (list {$vein styl}))}`. I'm not sure how it could fit with `++tanq`.

Thoughts?

**Comment by cgyarvin** [comment]
I don't know enough about the usage of background colors.  I would ask: do
any IRC clients, etc, use these?  Are they universally supported by modern
ANSI terminal sequence recognizers?

The four-letter-word game isn't any fun unless you actually have to stick
to Scrabble words.  I would suggest: ++tint, ++deco, ++styx.

I am happy to dispute your feeling that colored output should be available
at a lower level.  I think it's really only for interactive use.  The use
of a ++tank (or hopefully soon ++tanq) is that it gives the programmer very
little leeway to style the output; in fact, ++tanq is even more easy to
build and restrictive for a reason.  Eg, a Hoon AST (twig) is a tree and
++tank builds trees, but a ++tank is not a pretty-printer for Hoon.

There are two kinds of text output: interactive and diagnostic.
Interactive output goes to the console as a sole-effect.  Anything a
generator produces is diagnostic output -- or at least, that's how we think
about it now.  The primary demand of diagnostic output is that it never
breaks, ever.  Nothing is more infuriating than a crash in rendering your
diagnostics.  So it has to be incredibly easy to generate, simple and
stupid, which ++tank is and ++tanq is even more.  I wouldn't want to go in
the opposite direction.

You could certainly imagine, however, a mark transformation that
transformed your data structure either to a tank, or to a styled text
document, or perhaps to HTML.  On the web you'd see HTML, in a terminal
styled text.  So I'm not saying that styled text output from generators is
impossible; I would do the interactive use case first.

As for the actual molds, your design is perfectly serviceable.  But most
styled text is likely to be just text.  So going from "foobar" as ++tape,
to "[[~ ~ "foobar"] ~]" as ++styl,  is a little annoying.  What about:

++  tint  ?($~ $r $g $b $c $m $y $k $w)
++  deco  ?($~ $bl $br $un)
++  styx  (list $@(@t (pair (pair deco tint) styx)))

What did we do here?  We disambiguate an unstyled atomic text block against
a styled subtree.  So "foobar" is also a ++styx.  We pair the color and
decoration, because they may be built as an integrated style.  We allow
text atoms of any length, so ['foobar' ~] is a ++styx as well.  Then the
new sole-effect page is {$sty p/styx}.  You could even make the deco and
tint units, creating snazzy cascading styles (~ inherits the parent's
style).

Also, at least as important as colored output is a colored *prompt*.  This
would certainly help with the constant prompt confusion we suffer from...
fortunately this is also a sole protocol.

Helpful?  Thoughts?

**Comment by juped** [comment]
Background colors are boring and normal. It's things like 256-color mode that are support nightmares. (I recommend not trying to support `ESC[20m`, even though it goes with our German grouping dots.)

If you feel like demolishing sole-effect and its companions and rebuilding them in your own image, give it a try - you may end up having to, especially for prompts. (Turning syntax errors from a bell that forbids to a red highlight that suggests is the biggest use-case for colors.) Don't do it just to do it, though.

**Comment by joemfb** [comment]
Thanks! That all makes sense, and is a big help.

Adding background colors, we get:

```
=x |%
++  tint  ?($~ $r $g $b $c $m $y $k $w)                 ::  text color
++  deco  ?($~ $bl $br $un)                             ::  text decoration
++  styl  (trel tint deco tint)                         ::  bg/deco/fg
++  styx  (list $@(@t (pair styl styx)))                ::  styled text
--
```

`++styl` is a triple ordered by reverse (expected) frequency -- that is, I expect foreground colors to be the most common use-case: 

```
``%r
`[%br %r]
```

And we'll need this, of course:

```
++  mtrx  [%k `%g]
```

There's a little black magic in that $@ mold! I spent time testing variants with an explicit tape (`?(tape (pair styl tape))`, `(list ?(tape (pair styl styx)))`, etc.) before realizing that all my use-cases were already covered:

```
^-(styx:x "foo")

^-(styx:x ~['f' [``%r "o"] 'o']))
^-(styx:x :(welp "f" [``%r "o"]~ "o"))

^-(styx:x :(welp "foo" [``%r "bar"]~ [``%g "baz"]~))
^-(styx:x ~[[``%r "foo"] [``%g "bar"] [``%b "baz"]])
```

As for inherited/cascading styles, I don't think we need a `++unit` -- there's already an outer list, so the only reason to nest is to inherit. And both `++tint` and `++deco` already include null. In other words, I'd expect these examples to render the same:

```
^-(styx:x ~['f' [``%r ~['o' [`[%un ~] "o"]]]])
^-(styx:x ~['f' [``%r "o"] [`[%un %r] "o"]])
```

As I described in #214, `%sole-effect` is rendered via `%dill-blit %out (list @c)` and `%give %blit ~[[%lin (list @c)] ...]`. (Note: `:talk` cheats with `++slog`, at least for some use cases...) It seems simplest to amend `++dill-blit` with something like:

```
{$klr (list (pair styl (list @c)))}
```

(and maybe short-circuit `++blit`?)

That move would be produced by flattening `++styx`, applying `++trip` and `++tuba`, reifying inherited and implicit `++styl`, and splitting long lines into multiple moves.

Interpreting that move will obviously require enhancements to `term.c`: what does the upgrade path look like for a change that affects `bin/urbit` and Arvo? Is there a mechanism for graceful degradation (such as a facility within Arvo to probe the binary for capabilities), or do you just push the breaking change and announce that everybody needs to build?

**Comment by joemfb** [comment]
My cascade proposal works fine for foreground/background colors, which don't compose, but not so well for decorations, which do ...

Not sure how to handle that, maybe reorder `++styl` and make `++deco` a unit ...

```
++  styl  (trel (unit deco) tint tint)                  ::  deco/bg/fg
```

**Comment by joemfb** [comment]
I should say that foreground/background colors don't *respectively* compose ...

**Comment by joemfb** [comment]
Since decorations need to compose, the new `++dill-blit` page would need to be:

```
{$klr (list (pair (trel (set deco) tint tint) (list @c)))}
```

If decoration composition ends up being a common requirement, it might be simpler for `++styl` to also be `(trel (set deco) tint tint)` ...

**Comment by cgyarvin** [comment]
You seem well enough engaged with this problem, so please consider these
suggestions no more than advisory...

I kind of want [bg fg] to be a pair.  But it would be nitpicking.

I considered regarding the default in your ++tint and ++deco as a unit
case.  I don't think that's right, though.  If it was right, it's a little
tacky to build in the null to a data structure; ++deco should be {$bl $br
$un}, etc.  If it's *not* right, "default" actually means something
semantically; it's a mysterious color or decoration defined by the terminal
but not by the protocol.  In this case, `~` should *not* inherit, because
then there's no way to get back to "default" within a nested span.

It would be ideal to get the breaking change in sooner rather than later,
because we have a big breaking change scheduled for August.  Admittedly it
doesn't change the term.c interface.  But there is simply no way to upgrade
the Urbit interpreter over the wire.

Alternatively, %blit could apply the ANSI codes itself and just rely on
them slipping gracefully into term.c, even though this is architecturally
very bad.  On the other hand, it could keep the change non-breaking.

~& is never output and nothing, including :talk, should rely on it :-)

I forget where splitting of long lines happen.  Isn't it performed at the
very end in term.c?  If so, I would keep it that way.  It's true that the
terminal tells us its preferred line width, but...

**Comment by joemfb** [comment]
You're right about the unit case -- I was trying too hard to keep it minimal ...

To the best of my knowledge, lines are wrapped in `drum` via `++ta-tan` and `++se-dump`. I expect I'll need to the same for `++styx`.

Here's a generator implementing your suggestions and demonstrating inheritance, conversion to `++dill-blit`, etc.:

```
:-  %say  |=  *  :-  %noun  =<
=+  ^=  casts
  %-  limo
  :~  ^-(styx "foo")
      ^-(styx ~['f' [```%r "o"] 'o'])
      ^-(styx :(welp "f" [```%r "o"]~ "o"))
      ^-(styx :(welp "foo" [```%r "bar"]~ [```%g "baz"]~))
      ^-(styx ~[[```%r "foo"] [```%g "bar"] [```%b "baz"]])
      ^-(styx ~['f' [```%r ~['o' [[`%un ~ ~] "oz"]]]])
      ^-(styx ~['f' [```%r "o"] [[`%un ~ `%r] "oz"]])
  ==
::
::  blit length check (for wrapping):
::    ,:(roll (turn a |*(a/(pair) (lent (tail a)))) add)
::
%+  turn  casts
|=  a/styx
[(to-tape a) (to-blit a)]
::
|%
++  tint  ?($~ $r $g $b $c $m $y $k $w)                 ::  text color
++  deco  ?($~ $bl $br $un)                             ::  text decoration
++  styd  (pair (set deco) (pair tint tint))            ::  decos/bg/fg
++  styl                                                ::
  (pair (unit deco) (pair (unit tint) (unit tint)))     ::  cascading styd
++  styx  (list $@(@t (pair styl styx)))                ::  styled text
::
::  sole-effect:
::    {$klr p/styx}
::
::  dill-blit:
::    {$klr p/(list (pair styd (list @c)))}
::
++  to-tape
  |=  a/styx  ^-  tape
  %-  zing  %+  turn  a
  |=  a/$@(@t (pair styl styx))
  ?@(a (trip a) ^$(a q.a))
::
++  to-blit
  |=  a/styx
  =<  (reduce (flatten a))
  |%
  ++  flatten
    =|  b/styd
    |=  a/styx
    ^-  (list (pair styd (list @c)))
    %-  zing  %+  turn  a
    |=  a/_?>(?=(^ a) i.a)
    ?@  a  [b (tuba (trip a))]~
    %=  ^$
      a  q.a
      b  :+   ?~  p.p.a  p.b
                ?~(u.p.p.a ~ (~(put in p.b) u.p.p.a))
              ?~(p.q.p.a p.q.b u.p.q.p.a)
              ?~(q.q.p.a q.q.b u.q.q.p.a)
    ==
  ::
  ++  reduce
    |=  a/(list (pair styd (list @c)))  ^+  a
    %+  reel  a
    |=  {a/_?>(?=(^ a) i.a) b/_^+(a ~)}
    ?~  b  [a]~
    ?.  =(p.a p.i.b)  [a b]
    [[p.a (weld q.a q.i.b)] t.b]
  --
--
```

It produces

```
~[
  ["foo" ~[[p=[p={} q=[p=~ q=~]] q=~[~-f ~-o ~-o]]]]
  ["foo" ~[[p=[p={} q=[p=~ q=~]] q=~[~-f]] [p=[p={} q=[p=~ q=%r]] q=~[~-o]] [p=[p={} q=[p=~ q=~]] q=~[~-o]]]]
  ["foo" ~[[p=[p={} q=[p=~ q=~]] q=~[~-f]] [p=[p={} q=[p=~ q=%r]] q=~[~-o]] [p=[p={} q=[p=~ q=~]] q=~[~-o]]]]
  ["foobarbaz" ~[[p=[p={} q=[p=~ q=~]] q=~[~-f ~-o ~-o]] [p=[p={} q=[p=~ q=%r]] q=~[~-b ~-a ~-r]] [p=[p={} q=[p=~ q=%g]] q=~[~-b ~-a ~-z]]]]
  ["foobarbaz" ~[[p=[p={} q=[p=~ q=%r]] q=~[~-f ~-o ~-o]] [p=[p={} q=[p=~ q=%g]] q=~[~-b ~-a ~-r]] [p=[p={} q=[p=~ q=%b]] q=~[~-b ~-a ~-z]]]]
  ["fooz" ~[[p=[p={} q=[p=~ q=~]] q=~[~-f]] [p=[p={} q=[p=~ q=%r]] q=~[~-o]] [p=[p={%un} q=[p=~ q=%r]] q=~[~-o ~-z]]]]
  ["fooz" ~[[p=[p={} q=[p=~ q=~]] q=~[~-f]] [p=[p={} q=[p=~ q=%r]] q=~[~-o]] [p=[p={%un} q=[p=~ q=%r]] q=~[~-o ~-z]]]]
]
```

If this is amenable to you, I'll get started on a PR.

**Comment by joemfb** [comment]
Closing, since the discussion has moved to #216 and http://urbit.org/fora/posts/~2016.8.2..21.19.29..2ab8~/
