### ISSUE TITLE
;who not working

### ISSUE THREAD

**Issue by whereswaldon** [urbit/arvo#215]
I just spun up my planet today, and I joined ~dozbud/urbit-meta. The join went fine, but `;who` does nothing at the talk prompt. I get:

```
--------------| ;who
```

with nothing after it... To replicate, maybe just spin up a comet and join urbit-meta, then try ;who?

**Comment by ohAitch** [comment]
This and urbit/talk#30 are likely caused by presence notifications being
turned off on the server, as a temporary measure to handle load. I don't
know what the load is like currently, and would hesitate to turn them back
on without some manner of throttling in place; but at least at some point
this was an intentional counter to /urbit-meta users connecting,
which sent everyone a notification that they've connected, timing out
before they could get said notification, which sent everyone a notification
again that they'd disconnected, and reconnecting upon noticing the
subscription drop, which etc.

**Comment by Fang-** [comment]
Now that presence notifications are back on again, `;who` works fine, and so does webtalk's membership list.

This and urbit/talk#30 can be closed.
