### ISSUE TITLE
fuse-loop on product of limo

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#333]
Apparently there's a bug where a fuse-loop error gets reported on the product of a `++limo` call. Context seems to influence this.

For an example of what does/doesn't compile, see this Hoon file: [Pastebin](http://pastebin.com/qTdzkfby)

**Comment by joemfb** [comment]
`++limo` makes a list out of a "not-list", but you're prepending to something that's already a list. A cast will serve you better:

```
=/  a (limo [1 2 3 ~])
=/  b  0
^+(a [b a])
```

IMO, `++limo`, `++ly` and other constructors are only fit for simple examples with literal nouns. Anything more complicated (or more permanent) and I'd always cast.

Even the example about looks better with a cast instead of limo:

```
=/  a/(list @ud)  [1 2 3 ~]
```

**Comment by Fang-** [comment]
The docs already mention they're for use with non-lists only, so I guess I should've paid more attention.  
"Turns a null-terminated tuple into a `++list`."

Closing this. If anyone thinks this warrants special mention in the docs ("don't try to listify lists", etc.), reopen this and I'll put it in.
