### ISSUE TITLE
forks of cells can be redundant

### ISSUE THREAD

**Issue by joemfb** [urbit/arvo#366]
as discussed in #361

```
> =/(a *?($ash $elm) ^-(foot [a *twig]))
nest-fail
> =/(a *?($ash $elm) ^-(foot ?:(?=($ash a) [a *twig] [a *twig]))
[%ash [%$ p=0]]
```

courtesy of @ohAitch 

```
> `$%({$& $~} {$| $~})`*{? $~}
/~zod/home/~2017.3.2..20.42.50..0b14/sys/vane/ford:<[1.207 24].[1.207 52]>
-need.?({$.n $~} {$.y $~})
-have.{?($.n $.y) $~}
nest-fail
```

**Comment by joemfb** [comment]
It seems like the simplest fix would be to reduce the span:

```
|=  sut/span
?.  ?&  ?=({$fork *} sut)
        (~(all in p.sut) |=(a/span ?=({$cell *} a)))
    ==
  sut
=/  sep
  %+  roll
    (~(tap in p.sut))
  |=  {a/span b/(pair (set span) (set span))}
  ?>  ?=({$cell *} a)
  [(~(put in p.b) p.a) (~(put in q.b) q.a)]
?:  ?=({* $~ $~} p.sep)
  [%cell n.p.sep $(sut [%fork q.sep])]
?:  ?=({* $~ $~} q.sep)
  [%cell $(sut [%fork p.sep]) n.q.sep]
sut
```

**Comment by juped** [comment]
Possibly interesting note: this problem doesn't exist for face spans, e.g. a fork where every case is a cell with a head called 'p' can be fished by 'p'.

**Comment by joemfb** [comment]
I've implemented this reduction in `++fork`:

https://github.com/urbit/arvo/compare/master...joemfb:reduce-fork-cell

but there are complications... I can't `|reset` with an un-jetted `++fork` (`dig: over`), so I updated the jet (I'm not particularly confident in the reference counts):

https://github.com/urbit/urbit/compare/master...joemfb:reduce-fork-cell

I can use this, very carefully:

- new fakezod from urbit/arvo@4288aab089c46cc9fb575c37e393137f6ec339f6, urbit/urbit@cee04c794bb596484e475a560895c516441bda31
- ctrl-d, checkout reduce-fork-cell, make, restart

```
> =/(a *?($ash $elm) ^-(foot [a *twig]))
[%ash p=[%$ p=0]]
> `$%({$& $~} {$| $~})`*{? $~}
[%.y ~]
```

But I can't `|mount %` (`bail: oops`). The big problem is that this breaks `++welp`. I can run `+metal` after adding some casts, but I can't compile `++welp` itself ...

/cc @cgyarvin

**Comment by joemfb** [comment]
@juped, that is interesting. And it leads to my next question: is span production the wrong place to do this? Should it go in `++nest:ut` instead?

**Comment by juped** [comment]
I think of it as a nesting question. I'm embarassingly unfamiliar with the actual `++ut`'s nest, having only reimplemented it from scratch, not read it.

**Comment by joemfb** [comment]
Do you have a link to your implementation?

**Comment by juped** [comment]
(The clear answer seems to be yours, pushing forks outward, but only at typecheck time, but I haven't spent the several minutes thinking about it that it deserves)

**Comment by juped** [comment]
Law: `[%cell [%fork a b] c]` can have the fork pushed outward, becoming `[%fork [%cell a c] [%cell b c]]`.

Theorem: If `s` nests in `[%cell [%fork a b] c]`, then `s` nests in `[%fork [%cell a c] [%cell b c]]`.
Proof: It follows from the hypothesis that `s` is a cell or `%void`, the latter case being trivial. If `s` is a cell, then it nests if both head `s_h` and tail `s_t` nest. Since `s_h` nests in `[%fork a b]`, `s_h` nests in either `a` or `b`, assume w.l.o.g. that `s_h` nests in `a`; `s_t` must nest in `c`. So `s` nests in `[%fork [%cell a c] [%cell b c]]` because it nests in `[%cell a c]`.

Therefore you can push all forks outside cells prior to nest checking without making any nest relationship invalid that was already valid; and we see that it usefully makes additional things valid.

But with the implementer's hat on, a normalizing pass on spans is basically a brand new phase of compilation.

**Comment by cgyarvin** [comment]
Yeah.  This is a great conversation, but my desire to mess around in language guts to improve this area is kind of small right now.

Really, ++ut needs a rewrite -- but not now.  I mean, if someone had this work all done and stuff...

**Comment by joemfb** [comment]
With all due respect to your disinclinations, I can't seem to let this one go ...

While an additional phase to normalize spans would be great, I don't think it's strictly necessary. Instead, I've implemented a just-in-time reduction for forks of partially-redundant cells in `nest`:

https://github.com/urbit/arvo/compare/master...joemfb:nest-fork-cell

https://github.com/urbit/urbit/compare/master...joemfb:nest-fork-cell

The naive jet implementation (first commit) worked for my test cases, and could `+metal`, but crashed with `bail: meme\n bail: 3` on `|reset` (presumably due to the insane number of allocations for every book). I've made it efficient enough to `|reset`, and everything seems to work without any issues or regressions. But there is a slightly noticeable delay in running my examples in the :dojo.

I have no idea if this is actually worth integration, and understand that there would be some risk in doing so. But it's a relatively isolated change, and shaves off a minor but pretty sharp edge ...

**Comment by cgyarvin** [comment]
I guess what I would say is that I worry that making the type system more
powerful here makes it harder to use.

Hoon's type system is inherently conservative.  It guarantees that your
result is ok if it says yes, but it says no whenever it likes.  Its rules
aren't optimized for being as powerful as possible.  They're optimized for
being as simple and easy to remember as possible.

You've expanded a straightforward two-line treatment of %fork in ++nest
into what, fifteen?  If that made Hoon able to find everything that
mathematically should compile, and make it compile, great.  But all it does
is find a single reasonably common corner case, and turn it into an
exceptional case that everyone needs to remember.

I'm not absolutely wedded to this argument, but if there is a
counterargument I'd like to hear it...

**Comment by joemfb** [comment]
I understand your argument against *complecting* the type system, but I don't think that's what I'm doing. `nest` is designed to avoid false positives, and is free to produce false negatives. I'm simply arguing that this particular false negative is an unnecessary pain in the ass.

This is a totally selfish argument! I'm only here because I wrote this, and it's ugly: https://github.com/urbit/arvo/pull/365/files#diff-3188c10b79fc239c922713458783fee5R6195

While I assume this alternative would compile,

```
=;  ram/twig
  ?:(?=($ash) [-.a ram] [-.a ram])
|-  ^-  twig
?~  q.gen  p.a
[%aka p.i.q.gen q.i.q.gen $(q.gen t.q.gen)]
```

it has an unnecessary face/pin *and* an unnecessary branch. But At least it doesn't call the mold ... Given the current `nest`, how you would write it?

More generally, I don't see my proposal as increasing anyone's cognitive burden. I'm taking a case (admittedly somewhat rare) that requires non-obvious, redundant gymnastics, and removing it. Who would be inconvenienced by this exercise?

This is also entirely different from my first proposal, which made only because it was simpler, and seemed more elegant (perhaps through motivated reasoning). Changing the product of type-inferencing is obviously disruptive -- let alone that I produced apparent false negatives!

I agree that this implementation is not obvious, but the logic seems bulletproof. I don't think it would be the only piece of Hoon with these properties ;)

**Comment by joemfb** [comment]
Also, I forgot this:

@juped, your theorem is the opposite of what I did in my first example. I reduced the "redundant" fork to a cell, you pushed the fork out of it's containing cell. Your logic strikes me as correct, and mine obviously was not. But this change would indeed require a full normalization of spans ...

Thanks for writing it up!

**Comment by joemfb** [comment]
@chc4 suggested in `:talk` that @juped's solution could be implemented in `++cell` with minimal disruption, so I've gone ahead and done that. 

https://github.com/urbit/arvo/compare/master...joemfb:expand-fork-cell

(the compiler needed a surprising number number of assertions here -- another rabbit hole to fall down later ...)

https://github.com/urbit/urbit/compare/master...joemfb:expand-fork-cell

My examples work correctly, and the performance is noticeably better than the `nest` solution:

```
> [p:!>(*$%({$& $~} {$| $~})) p:!>(*{? $~})]
[#t/?({$.n $~} {$.y $~}) #t/?({$.n $~} {$.y $~})]
> `$%({$& $~} {$| $~})`*{? $~}
[%.y ~]
> =/(a *?($ash $elm) ^-(foot [a *twig]))
[%ash p=[%$ p=0]]
```

This also works much better than my initial `++fork` proposal; I can `|reset` or `+metal` and boot, with only three problems (at least, so far):

- It doesn't like something in lib/twitter:

```
/~zod/home/0/lib/twitter:<[44 5].[44 12]>
```

- There's a typeswitch in :dojo that doesn't work:

```
/~zod/home/0/app/dojo:<[554 29].[554 42]>
```

- And there's a nest-fail in %eyre, which prevents (re-)installation:

```
/~zod/home/~2017.3.13..02.57.59..b201/sys/vane/eyre:<[803 18].[823 43]>
```

Here's the log for the `|reset`: http://pastebin.com/cp7uuwCR

And the log for the pill:  http://pastebin.com/PBCaFY0T

So this is something else to think about. If nothing else, it's been good practice for me with some lower-level functionality ...

**Comment by cgyarvin** [comment]
@takes a look at the code...

Yeah well.  It's a fun thing to play with but nothing that looks like this
is going in ++ut (not that the problem is fundamentally aesthetic).

Basically there is an almost infinite set of ways to find special cases
which "obviously" match but which the conservative algorithm can't detect.
Many of these special cases can be added to the conservative algorithm.
This creates a language which is not easier to use, but harder, because the
rule is now not "stuff like this doesn't work" but, rather, "stuff like
this doesn't work, with the exception of X and Y and Z, which we
special-cased to make work."  You then have this horrendous learning
experience where you try X and Y and Z and they work, so your brain goes to
"++nest is magic and always works."  Then you try W and it doesn't work,
and you're like, wha?

Whereas now, when you see this X not work, you actually gain a sort of
insight into how conservative ++nest is when it's being conservative.  You
can then make your peace with this, because you have no choice.  Learning
that X doesn't work actually strengthens your mental model of the very
simple and limited power of ++nest.

**Comment by chc4** [comment]
For the record, I kinda agree with Curtis about this. Either ++nest should always work if types should nest, or it doesn't. Either changing the type system so it uses a smarter algorithm overall (and is probably slower and more complex), or have it minimal and have the programer do the leg work.

On the other hand, what other special cases are there in nest? Forks and cells and unification are basically the only things that I can think of, because that's basically all that Nock is.

Really, the problem is that it's hard to tell what the problem you're hitting is currently, and that's only because want/got is disabled in nest-fails. :(

**Comment by joemfb** [comment]
Well, this repository is an existence proof that both `++play` and `++nest` are perfectly suitable in their current form. And *"don't write molds with overeager/redundant forks"* is perfectly actionable advice. I'll live to play another day ...
