### ISSUE TITLE
Electroplating doesn't fix interior faces of the sample

### ISSUE THREAD

**Issue by chc4** [urbit/arvo#391]
This bug is kinda notorious, but I've been running into it left and right recently. Wet gates have a major problem where, when being called, it doesn't re-set interior faces when doing callsite type checking. A trivial example of this is `(biff (some [1 2]) |*({p/* q/*} p))` - it will give you a `-find.p`, because `_+<` is just `{@ud @ud}` instead of `{p/@ud q/@ud}` like you expect.

This basically means that highly generic Hoon code is impossible, since you can only ever use trivial data structures or else you are stuck using lark syntax to access your function parameters. There are even some cases in the stdlib where this bug is tripped: You can't actually do ` (~(put by *(map @ud @p)) [1 ~zod])` without getting a `-find.b` from inside `++put:by` because of this, instead needing to use `[b=1 c=~zod]`. `(oust [1 2] "abcd")` likewise doesn't work, due to faces on the indexes.

I'm pretty sure this used to work fine in 164k Hoon under vulcanization, but was sadly broken...and I have no clue what part of the compiler even touches this, never mind how to grok it.

**Comment by cgyarvin** [comment]
"Bug" isn't quite right.  A bug is inexplicable behavior.  It is possible
to explain this behavior.  But it could be easier.

For those without all the historical context, here is the problem in Hoon.
When evaluating an arm (functional attribute), we have two spans (types) to
work with: the type of the actual subject we're working with, and the type
of the formal subject the arm was compiled against.

Most arms are dry, which means we solve the problem as follows: test that
the actual subject is a special case of the formal subject, then evaluate
with the formal type.

Some arms are wet, which means they work like macros -- we evaluate with
the actual subject.  As we evaluate the arm, we also keep track of the
formal subject, because we need to know that the arm's implementation
(which was compiled against the formal subject) will work with the actual
subject.

But we can't use *exactly* the actual subject, because it's missing
critical metadata from the formal subject -- eg, the faces in a gate's
sample (argument names to a function).

Hoon unfortunately has a long history of shitty solutions to this problem.
Our first shitty solution was vulcanization, which involved modifying the
code in the arm to put the missing faces back in.  This was dogshit and
we're not going back to it.  Our current shitty solution is electroplating,
which uses the twig (AST) structure of the caller to write into the sample
instead of over it.

After thinking about the issue a little more, I think the only truly
correct solution is to keep the problem within the type system.  It's
necessary to define a function which combines two subject spans, one of
which is the formal type and one of which is the actual type, and produces
a span to evaluate the arm against.

This problem is harder than it looks.  It is of course necessary to obey
the invariant found in all ++ut span traversals: a lazy `%hold` must be
treated as its expansion.  Of course, if types evaluate indefinitely, their
expansion has to be pruned.  It is cheating to restrict formal samples to
`{a/* b/*}` and the equivalent.

One idea I had: use nesting tests as a way to prune.  Require that the
actual type nests within the formal type.  (We should be doing this anyway
but we aren't.)  Where the two nest mutually, resolve to the formal type.

You can see the problem in ++fire:ut.  This is also where any solution to
this problem.  (`%ash` arms are dry, `%elm` are wet.) ++fire is
unfortunately jetted, but the jet is very simple (watch out for the fact
that jets can be called by other jets).

We should be using urbit.org/fora for this conversation... I'll give you a
head start, then post it there :-)

**Comment by ohAitch** [comment]
I think my stance on this is it isn't quite a bug, but simultaneously is
the obvious worst bug currently in the hoon language
(The ^~ "uninitialized variables" behavior is a strong contender)

Nesting is not checked because wet gates are frequently used for
higher-order programming, and we don't yet have a "soft" nest tester that
doesn't respect core variance.

**Comment by cgyarvin** [comment]
I will accept patches for either of these things, bugs or not.

**Comment by chc4** [comment]
I've been thinking about this a bit, and played with writing the function you outlined, and am not sure how it would actually work in practice.

Consider if you have the gate `|*(a/(list) a)`. If you call it with `{a/@t b/@p c/$~}`, the concrete type that you have to typecheck against has to be a `(list ?(@ @p)`, which seems mildly impossible to generate. My current method for resolving %holds is to pick which fork the sample is a subtype of, recurse and replace that case, and re-build the fork with the other cases so it wouldn't end up with a mint-vain. But that gives me a type like `#t/?($~ {i/@t t/?($~ {i/@p t/$~})})`, which doesn't work since each element is not a fork.

The only thing I can think of is some weird two-pass system for if hitting a hold add the type of elements it narrows to a set, and have each element it narrows end up being a fork of all those cases, but I'm not convinced that would actually work correctly.

Here's some code to show what I'm talking about: https://gist.github.com/chc4/ae0fbea6c3a0239c5c8bf626e73b5fcf

(Thinking about other cases of what to do makes me appreciate how hard this actually is. If you try to call with a `(pole @)`, for example, you actually have to write an adapter for the hold's twig that fixes the result, along with brain surgery the hold span...)

**Comment by cgyarvin** [comment]
When student fall silent, then master begin to speak!  I am not sure I
quite have a solution to this problem, but maybe I can advance us a little.

First of all, there's a pretty straightforward fix to electroplating which
would make, for example, ++oust work.  This is to modify ++open:ap for the
%open case so that it recognizes not just flat tuple structure in the
sample (as it does at present), but also nested tuple structure.  Ie, we
understand (foo [a b] c) as well as (foo a b c).  The correct way to do
this is to write another ++ap arm that exposes explicit tuple structure
(eg, works for :_(b a) as well as [a b]).

The problem, as I recall, is that when I applied this change -- the tools
for which you can see commented out in ++hail and ++half -- it made
compilation too slow.  Unfortunately I forget exactly why -- but there is a
comment noting that, across all of Hoon, %= should really default to %_
(checking for a match).

I think %= should always be %_ (and would improve error feedback).  I can
sort of see, intuitively, why the combination of these things might cause
performance problems.  But I think what actually happened is that I triaged
this line of work.  It could be profitably picked up again, I imagine.
Certainly it's outrageous that ++oust doesn't work.


On the other hand, it might be interesting to actually solve the problem I
posed previously, working purely at the type-system level.  If so, four
points.

One, let me sharpen the definition of this "rectification" problem
slightly.  We have two spans, `sut` and `ref`.  Our mission is to produce a
modified `sut` which has exactly the same semantics as the old `sut`, but
*in its cosmetic facial structure* follows `ref`.  Moreover, rectification
only adds cosmetics from `ref` to `sut` -- it doesn't have to strip
superfluous faces off `sut` or anything.

Two, I reiterate that %hold is never a semantically meaningful signal.  In
theory, if you were writing this in Haskell you would never even see the
%hold.  No, actually if you were writing this in Haskell you'd have to use
the same manual laziness as in Hoon, because you need to intercept
repetition.  Look at ++moot:ut for classic repetition intercept.

But even the fact that we test for repetition on a %hold, in many ++ut
algorithms, is kind of a coincidence.  You can't repeat without cells, so
we could just as easily test on every %cell.  Honestly, that might even be
the right design, though I don't think it would change the semantics.

The right thing to do with %hold: expand it.  Also, ++mull has no place in
this algorithm.  (The span we are creating will become `dox` in a later
call to ++mull.)  Look at ++nest:ut (subtype testing) for a good example of
code that traverses two spans in tandem.

Three, I think we can require that `sut` be a subtype of `ref`.  We don't
test for this right now, but anything that violates it is kind of a
perversion.  This considerably reduces the set of weird special cases you
have to think about.

Four, I don't think we have to care about rectifying within repetitions in
`sut`.  It would be cool to be able to turn a ++pole (nameless list) into a
++list.  But it's not required.  To "change" a repetitive span (as opposed
to just expanding a %hold, which is totally fine if you don't do it
repetitively) might actually be possible, if we were super-clever and not
afraid to build our own recursive gene to wrap up in a new %hold.  In the
past this would have frightened me too much, but now I think it's perfectly
legit.

**Comment by ohAitch** [comment]
> doesn't have to strip superfluous faces

So then I'm guessing stuff like (|*((list) ...) [j=1 r=[j=2 r=[j=3 r=~]]])
is unsupported? Because if you don't strip them, the stray r's will prevent
your i.t.t from resolving. (Unless you mean to stick the whole shadow
structure under layered =, side-names?)

> I think %= should always be %_ (and would improve error feedback)
If you mean the .(a foo1 foo2) irregular form, and in general the meaning
of %= which is a prettier rune, I agree completely; but being able to
change things' types whatsoever without a full
manual destructure-restructure is too useful, in constructing types
themselves. See e.g. |=  a/foo  ^+  a(n.z.x ~), or conversely the
TMI-workaround ?~(foo ... =>(.(foo (list ...)) ...)

> Three, I think we can require that `sut` be a subtype of `ref`.
If we ignore variance, sure; but higher-order wet gates need to be able to
read the samples of their arguments, most prominently for ;~ to work at
all.

**Comment by chc4** [comment]
Hm, ok. My thoughts were much too ambitious, which makes sense. It'd be nice to have a list of testcases that should work, and some that shouldn't under the new scheme. On that note: other than checking the two types "softly" nest (for @ohAitch 's core variance), is there actually anything that has to change in (this new code)[https://gist.github.com/chc4/ae0fbea6c3a0239c5c8bf626e73b5fcf]? Something fancy like fixing core arm return types is possible (for structural genericity of interfaces), but that's really really obscure shit and probably doesn't matter.

I also feel like removing existing faces is correct, so that lark access for function calls works correctly. I recently wrote `    =+  p=(res i)
    ((next -.p) +.p)` for example, and you can do `(add c=1 d=2)` just fine currently.

I'm not sure what the relevance of `%=` in this case is: `$call` expands into an `$open` which expands into `$bake` already. Do you mean to turn `$bake`'s expansion from `%=` to `%_` instead?

When does the typecheck actually run? Looking at it, I'm not sure why `(f 1 2)` works while `(f [1 2])` doesn't - the first one expands into a more verbose `$bake` that sets the two axis separately, but that should still destroy the faces on the sample...I'm not sure where to actually *place* the call to ++adapt for the typecheck.

**Comment by cgyarvin** [comment]
Not handling %hold is a special case of giving it special handling, which
is verboten.  You have to expand it.

You also have to account for the situation in which %sut and %ref have
matching faces, and they should merge rather than piling on top of each
other.

Look at the expansion of %open in ++open:ap.  It is not doing exactly what
you think it is doing.  To be exact -- it is not replacing the whole
sample, but rather individual legs of the sample.  And it uses the `,`
operator to replace behind the faces without destroying them.  Delicate
surgery is being performed, directed by the twig structure of the calling
code.

**Comment by eglaysher** [comment]
So after sitting down with Curtis to hammer this out (where he walked me back from trying to rewrite twig trees from spans in `%hold` handling), I came up with the following:

https://github.com/eglaysher/arvo/blob/makeover/gen/makeover.hoon

It seems to work in the major cases. The `$core` case remains unimplemented though.

**Comment by cgyarvin** [comment]
Some simple ways I would adjust this.  (I've been thinking about this
problem as well, I now believe it is solvable and you can't stop me when I
scent a kill.  I can write the code myself at this point, I think, but I
think it will be more fun for you.)

(0) The coding conventions of `++ut` are definitely suboptimal, but I have
a strong bias for matching conventions when I check in code.  From my
perspective, there are three levels of convention quality:

(A) Code with good conventions.
(B) Code with bad conventions.
(C) Code with no conventions.

When the patch doesn't match its context, if you think you are
incrementally improving (B) code to be (A), you are actually reducing it to
(C).  Fix conventions in big rigorous passes.  I realize this is
experimental code and not an actual patch, I am just providing a crotchety
warning.  It is definitely much easier to test code in a standalone
generator, but you can make it look the same.

(1) `$core` can just produce `outside` (or `ref` by `++ut` convention).
Remember that `ref` is the actual inferred span that describes the actual
data.  You can always just produce `ref`.  I guess it is not absurd to also
treat the payload as if it was the head of a cell, and recurse into it.

(2) `$atom` should also just produce `ref`.

(3) `?=($cell -.ref)` is perhaps gauche by `++ut` standards.  Like using
the dessert fork on your steak.  For one thing, a `$hold` needs to have the
same semantics as the `$cell` it expands to.  Or you could need to crack
open a face.  But the general principle is: don't interrogate the thing,
use the thing.  Asking what something is, is an antipattern.  How do you
get the head and tail of `ref`?  `++peek`, which can take the fragment at
any axis of any span.

(4) You commit the same betise under `$hold` itself -- your nesting test
here is superfluous, so far as I can tell.  And `$hold` is no more a
special case than `$cell`.  Yes, you are checking for a repeated pattern
under `$hold`.  But this is just convenience.  Every repeated pattern also
repeats through cells.  You can intercept repetition anyway.  But you can't
change semantics.  The lazy needs to be transparent.   Or the language will
behave extremely weirdly to the programmer.

(5) Your behavior on `$fork` is kind of weird, as you seem to be using
whether `++makeover` produces `%void` to filter the match.  This overloads
the power of `++makeover`.  The only test you need or should be using here
is `++nest`.  When we handle a `$fork`, our question is: which of the cases
in the `$fork` is actually shaped like `ref`?  Obviously fork cases in the
subject, our makeover template, are of no interest if they don't match
cases in the reference, our makeover victim.

Also with `$fork`, in binary span operations which involve both `sut` and
`ref`, we need to be careful not to get in a situation where we end up with
an n-squared sized fork.  This happens trivially with most trivial
traverses you can think of, so it's necessary to be slightly smart.
Basically, you cannot step into a fork without pruning it.

Here we have two real-world common cases, I think.  The first is where
`ref` is much more specific than the "inside" `sut`.  Obviously this
happens when `ref` is a concrete immediate noun.  In this case we can prune
`sut` easily with `++nest`.

But how do we prune `ref`?  I think there is no escaping a traverse that
works in sinister and dexter (`++sint` and `++dext`).  Sinister switches on
`ref`, dexter on `sut`.  We have just been describing a sinister traverse.
But before this sinister traverse, we could do a dexter traverse that
expands `$hold` and prunes `$fork`.

(6) The handling of `$face` needs to have two modes -- one shallow, one
deep.  Just use a loobean loop variable.  A mode bit.

Shallow mode compensates for the fact that nobody who calls a function puts
the names of the arguments as faces on the arguments.  You say `(add 2 3)`,
not `(add a=2 b=3)`.  So in shallow mode, when the subject has a face, you
always put the face on the reference.  Then you recurse into the reference
-- but you recurse in deep mode.

In deep mode, the reference noun could be something consed up, in which
case it will have no faces.  Or it could be an existing data structure, in
which case it does have faces.  You don't want to double those faces.
 `i=i=@` is not a good look.  So when the subject has a face, you have to
check for a matching face on the reference.  Again, don't write your own
interrogator -- `++find` will tell you everything you need.

This works fine unless your subject has a retarded structure like `x=x=@`.
But who is going to do that?

And finally:

(7) I think this whole problem is generally overblown (although I think it
should be solved), because I think in most cases cores that are
parameterized should be curried around their parameter molds.

For example: if we have `moo` which is a `(map foo bar)` and we want to be
able to write `(~(get by moo) goo)`, we need to throw `moo` and `goo` into
wet arms.

But if we could just write `(~(get (by foo bar) moo) goo)`, we could do
everything dry, except for the `++by` sample itself (the molds `foo` and
`bar`).  And this is normally the way we do genericity in userspace.  It's
perhaps less elegant, but it kills the problem stone dead by simply
avoiding it.  It is not notably less efficient.  But there is a small
convenience cost, which is why I think it's good to actually solve the
problem for the hoon.hoon containers.

Finally, we had "vulcanization" and "electroplating."  I suggest
"remodeling," or `++remo`.  Conventions are good!  Even if they suck.

**Comment by ohAitch** [comment]
> But if we could just write `(~(get (by foo bar) moo) goo)`, we could do
everything dry, except for the `++by` sample itself (the molds `foo` and
`bar`). And this is normally the way we do genericity in userspace.

Huh, I don't think I've ever seen that pattern before. Does it buy you
anything beyond not having to understand wet gates?

**Comment by cgyarvin** [comment]
Putting the molds into the core lets you just program with them normally
using dry gates.

Normally when you have `(map foo bar)`, within `++by` it's not trivial to
say: here's a gate which takes a `foo` and produces a `bar`.  You simply
don't have those molds.  So you gotta do weird shit.

**Comment by belisarius222** [comment]
Solved in Hoon 143.
