### ISSUE TITLE
Talk subscriptions stop on kernel restart.

### ISSUE THREAD

**Issue by eglaysher** [urbit/arvo#496]
When turning on my planet today, I started pulling down messages from /urbit-meta. I then got a kernel update and started %vega-ing. Talk stopped updating after the kernel recompile finished. This was worked around with a ;leave, ;join /urbit-meta.

**Comment by belisarius222** [comment]
Thanks for the bug report. I suspect this was caused by some bugs @Fang- has been fixing today, where ~marzod is not relaying messages to the other stars. If you're under ~marzod, you should probably `;leave /urbit-meta` and `;join ~samzod/urbit-meta`. If you're not under ~marzod, please let us know, because that could be a different bug.

**Comment by eglaysher** [comment]
I'm under ~binzod.

**Comment by Fang-** [comment]
Sounds like another case of "our subscription dropped, let's do absolutely nothing about it!"  
Currently working on rectifying that.

**Comment by Fang-** [comment]
As per #500, dropped subscriptions should always get picked back up.
