### ISSUE TITLE
Undocumented % rune.

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#518]
While browsing talk.hoon, I encountered the '%'. It seems it a list ship, deck, now.
In addition, when used from talk, it seems to also append some app related information. 
Moreover, things like when used in dojo %%, %%%, %%%% seems to peel off the head off the list. 

What is this, and is there any documentation on this?

**Comment by mikolajpp** [comment]
I would also like to note, than in the entire codebase there is only one line which uses this:
#L581 in talk.hoon:  wide:(vang & [&1:% &2:% (scot %da now.bol) |3:%])

which seems to assemble the hoon expression. Is it outdated, and if it is, what would be the equivalent?

**Comment by ohAitch** [comment]
It's a path syntax, in the vim sense. % is "current path", which in dojo is
the root /ship/branch/revision; if you're in a .hoon file it will have the
path to the source, and in dojo you can say =dir %/foo to get similar
behavior.

Whirlwind tour: /=== interpolates in a specific number of current-directory
segments, /=bar= mixes interpolation and a constant, /=(cat 3 %ba %zz)=
interpolates the result of a hoon expression. /==12% completes the rest of
the path, e.g. If you're at /~zod/home/14/app/foo /==12% gives you
/~zod/home/12/app/foo, /==12%% produces /~zod/home/12/app, and /==12%%/talk
makes /~zod/home/12/app/talk.

A particularly common form you'll see in apps is /(scot %p our)/home/(scot
%da now)/etc, since apps are compiled once but always want to get things by
the current revision (and tbh I'm not sure when the ship would ever
change). And in ren/files, /: %/subfolder and /: /===/constant happens a
bunch.

**Comment by mikolajpp** [comment]
Great, this explains a lot. 

What about `%%%` etc. though? Why does it peels items off the path?

**Comment by ohAitch** [comment]
% is ., %% is .., %%% is ../.., etc yeah.
