### ISSUE TITLE
Direct atoms and Urbit future in 64 bits

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#526]
I have been delving deeper into Hoon compiler utilities, and it seems like 4 words names get less and less meaningful (it is a feature!). I remember hearing that 4 letters correspond to one Vere word which is 32(31?) bits, hence it is a performance consideration. Is it any true?

What will happen then when we finally move to 64bits?
Will names get more meaningful?

(I also found some arms in hoon which are _not_ 4 letter length, ++ require etc. Are these taking a performance hit then? (as minuscule as it would be))

**Comment by cgyarvin** [comment]
It's quite a small performance advantage.

In most cases the 4-letter names should get cleaned up as hoon.hoon gets
rewritten.  This is mostly a research trick so that, when you don't know
quite what a thing is, you don't put energy into naming and you think about
things as what they are, not what they're called.

**Comment by mikolajpp** [comment]
Well, Hoon is especially readable, except for the parts where names start differing by one letter ;-)
But if that will get cleaned, then even better.
