### ISSUE TITLE
redirect loop on fora and other domains

### ISSUE THREAD

**Issue by belisarius222** [urbit/arvo#580]
When I try to login to [https://fora.urbit.org](https://fora.urbit.org), the site goes into a redirect loop on the login page. This even happens in incognito mode. I've also seen this happen on another Urbit-hosted site that used a different domain name, and it started after Fora was moved to a subdomain of urbit.org, so I suspect something is broken with auth redirects on nonstandard domains. Still just a hunch, though.

**Comment by Fang-** [comment]
Can confirm. A workaround I found earlier was to, on the your-ship.urbit.org sign-in page, paste in your code and hit return *real fast*, before it can redirect you.

Maybe a solution is to make sure that the sign-in page never redirects if the entered ship name matches the host? Since that seems to be what's happening here. Haven't done any detective work though.

**Comment by mikolajpp** [comment]
Also confirm. On my forum with custom domain name ships trying to login end up 
being stuck in the loop. Once they go back to for page, they are logged in. 

I have started working on UP3, so hopefully it will lead to fixing this.

**Comment by belisarius222** [comment]
I'm starting to suspect the location directives starting here:
https://github.com/urbit/tlon/blame/edf8ea92e12058d2907405a51f326c3fb6d66015/utils/nginx/sites-available/urbit.org#L319

**Comment by jtobin** [comment]
Closing this one as it no longer appears to be relevant.
