### ISSUE TITLE
Compiler should detect and optimize loop invariants

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#584]
```
=+  a=100
|-
?:  =(0 a)  a
=+  b=(add 1 2)
$(a (sub a b))
```

Stupid example, but it really shouldn't be evaluating `b` every single iteration, since it's static across all possible iterations.

@belisarius222 said that "if all you have is Nock 9's and no Nock 2's, maybe it's okay to optimize that. Probably easier to do in Hoon though."

**Comment by belisarius222** [comment]
I should add the disclaimer that I don't know what I'm talking about. @frodwith would have a much more erudite understanding of how to perform this optimization in Hoon or Nock, and whether it's worthwhile.

**Comment by cgyarvin** [comment]
This is really low priority -- or, to put it more correctly, falls into the
scope of a much more sophisticated compiler.

**Comment by frodwith** [comment]
This optimization is called constant folding, generally, and hoon is probably the place to do it because you have type information. In particular, %= is probably the thing to modify, and the modification probably involves calling ++musk on the generated nock 9 code.

**Comment by frodwith** [comment]
I suppose loop invariant code motion might also be the optimization you're aiming for. That's a much harder proposition when all you have is tail calls, and probably involves some real loop finding in the nock runtime (since you can't express honest-to-goodness loops in nock, and that's hoon's compilation target). I think that involves watching some running nock code and recording information about call targets at call sites. Tail calls could be turned into loops with an equality check to guard.

**Comment by ohAitch** [comment]
So what I'm hearing is "tracing jit"

**Comment by cgyarvin** [comment]
All this stuff is well and good, but you don’t do it haphazardly one thing at a time...

**Comment by frodwith** [comment]
Yes, a tracing jit :) . I agree with cgyarvin's comments about priority, just throwing in my two cents for posterity.

**Comment by jtobin** [comment]
Closing as I think this is too broad to be useful.  See:

> This [..] falls into the scope of a much more sophisticated compiler.
