### ISSUE TITLE
=* tistar should allow for optional type annotation

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#585]
`=*` is a rune strictly used for code readability, and being able to add in a type annotation seems to be in line with that.

Should help with sanity checks for both the writer ("I expect this thing here to be of this type") and the reader ("what type is the data that `p.q.r.s.dat` refers to again?").

**Comment by cgyarvin** [comment]
It definitely should.  It's one of those odds and ends I kept meaning to
get around to.  Actually a good little project for those who don't fear the
compiler.

**Comment by mikolajpp** [comment]
Just signalling, ~palfun got me on this. We will see what happens.
Anyway, I always kind of liked compilers, especially to-nock ones ;-)

**Comment by cgyarvin** [comment]
Good luck!  Probably not that hard :-)

**Comment by joemfb** [comment]
@mikolajpp, are you working this one? I'm looking for a target, so I'll take it if you're not.

**Comment by cgyarvin** [comment]
Lmk if you need help with compiler staging...

**Comment by mikolajpp** [comment]
@joemfb feel free. Working, but not in an immediate sense, as in I am reading through hoon.hoon for the first time...

**Comment by joemfb** [comment]
So, it appears I do need help with staging...

I've added a `%tstc` hoon to demonstrate what `%tstr` should become:
[arvo](https://github.com/urbit/arvo/compare/master...joemfb:tstr-toro) and
[vere](https://github.com/urbit/urbit/compare/master...joemfb:tstr-toro).

I can sync those changes, `|reset` or `+solid`, and everything works as expected:

```
> =`(a our a)
~zod
> =`(a=@ our a)
0
> =`(a=@ our =`(b=@p (mix (lsh 5 1 (end 5 1 eny)) a) [a b]))
[0 ~danweg-bosrym-dozzod-dozzod]
```

However, when I update the `%tstr` implementation to match `%tstc` in hoon.hoon
(and remove `%tstc`), I can no longer `|reset` or `+solid`. Specifically, I get
`%find` errors compiling zuse and the vanes -- the same errors regardless of
whether the changes are in vere, surprisingly enough (at least to me). I'm sure
we've discussed the staging procedure before (and I thought I had successfully
done it before), but I'm at a bit of a loss.

For the sake of clarity, here were my steps:

- boot a fresh fake-zod from master
- additive changes to vere
- additive changes to hoon.hoon, |reset, success
- mutative changes to hoon.hoon, no |reset, +solid fails
- *various failed attempts with and without mutative changes to vere*
- *feel stupid*

Separately, what do you think of bunting the model in `+bust` (the placeholder
which is to replace `+buss:ut`)? I'd prefer to do it in `+open:ap`, but it seems
like that would require an additional hoon to separate pre and post macro
expansion (due to the convention of calling `+open:ap` in a default case).

**Comment by cgyarvin** [comment]
Add the new form in one stage, and make anything that generates a hoon generate it.  In the next stage, remove the old form.

**Comment by cgyarvin** [comment]
Sorry, I mean: rather than removing the old form, replace it with the semantics of the new form under the original name.  Then remove the temporary standin.

**Comment by joemfb** [comment]
Thanks! I was clearly rusty...

**Comment by joemfb** [comment]
This feature was added in the language changes.
