### ISSUE TITLE
Moon connectivity depends on ~zod?

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#629]
On my moon, whenever I get `~zod not responding still trying`, it is almost always followed by `~planet not responding still trying`.

If I try `|hi` from my moon to my planet, or the other way around, it won't go through. On my planet, doing so prompts a `~moon not responding still trying` message to print.  
Once I get a `~zod is ok`, the `|hi` goes through.

This makes it seem like moons proxy their traffic through ~zod, which is definitely not something we want.

**Comment by jtobin** [comment]
Closing this one as it hasn't gotten any follow-up in over a year.

**Comment by joemfb** [comment]
We don't exactly proxy anything in ames, but we do forward packets in order to (re-)discover peers. And we do a lot of that, because we expire routes pretty quickly. Maybe a moon's route to its planet should not expire as quickly as other routes?

These issues/questions fall under ames tuning and optimization, which has not been attempted.

/cc @belisarius222
