### ISSUE TITLE
Can't query hall for "last x messages"

### ISSUE THREAD

**Issue by belisarius222** [urbit/arvo#643]
Original title: **web talk hangs if there are no messages**

The page chrome loads, but the spinner goes indefinitely. Instead, it should display something like "No messages in the last 6 hours."

**Comment by Fang-** [comment]
This is because of a limitation in Hall's subscription interface. Webtalk really wants to be asking "get me the last 50 messages", but Hall doesn't allow for that yet, so the best it can do is say "give me the messages from six hours in the past to now". If it finds any messages, it knows their message numbers and so can make more specific queries to load in more scrollback granularly. If it doesn't get any messages... it tries six hours further back, and just keeps on trying.

At first, I thought the only solution was to expand the `/circle` interface to allow you to ask for "x messages before y date".  
Just now, I realized that we could also solve this by expanding Hall's interface to allow you to ask for the number of messages in a circle.

The former is easier to use, you don't have to do multiple requests to get the data you want. The later serves other purposes too, and should be part of a larger effort to make metadata like that more easily accessible.
