### ISSUE TITLE
++tang is in reverse printing order

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#646]
Original title: *List of tanks prints in reverse order*

As can be easily observed in the final `sole-so` [here](https://github.com/urbit/arvo/blob/master/gen/moon.hoon).

Fixing this may or may not cause the issues to pop up anew in places that are currently `flop`ing their `tang`s to work around this.

**Comment by ohAitch** [comment]
Isn't ++tang formally defined as "in reverse order", for ease of adding
things to the bottom?

**Comment by Fang-** [comment]
Looking at the hoon.hoon, it seems you're right.

```
++  tang  (list tank)                                   ::  bottom-first error
```

I guess that turns this into a discussion on whether or not that is the "right" way to define it. If we're applying that rule to `++tang` for printing, them we probably should be applying it consistently to anything that we send out of userspace for the system to deal with.  
@cgyarvin's original new gall spec also has moves being sent out in reverse order, which would make gall consistent with this.

I'm still uncertain if that actually is the right call though. How does ease of adding stack up against the extra mental effort to keep in mind that an intended `[1 2 3 ~]` should be sent out as `[3 2 1 ~]`? I recall getting a bit tripped up by this in places in the past, though maybe just using the related patterns consistently can alleviate that.

**Comment by cgyarvin** [comment]
I have no strong opinions, besides the demonstrated fact that our current
handling of this is a sh*tshow.

**Comment by belisarius222** [comment]
A difference between stack traces and move lists is the incremental construction and modification of stack traces, compared to the monolithic construction of move lists.

I think move lists should be first-move-first. Constructing a list backward is slightly easier, but the reason moves are a list at all is that a list presents a natural linear traversal, which hints at its purpose. That natural traversal is first-to-last. Let's not complicate semantics just to ease the one-time construction of a piece of data. As for performance, I'm pretty confident one or two extra calls to `++flop` per event will be negligible in almost all cases.

For stack traces, the situation is a bit different, since that's a data structure whose primary purpose is to be modified incrementally, and can be thought of as storing the sequence of modifications. When you enter a new function, you add a new entry to the stack trace, then when you're done with the function you pop it off. That suggests more pinpointed lines of the stack trace should be at the front, meaning the stack trace should be stored in callee-caller order. The line where the error occurred should be the first element of the list. Also since this data structure gets modified per function call, performance should be a primary consideration.

How to display the stack trace can be a separate question from how to store it. I don't have an extremely strong opinion on this, but I think having the offending line at the bottom is generally more convenient in the terminal, so I'd pick that display direction and stick with it. If I recall correctly, there was some idea of a web user interface displaying latest information at the top, like https://urbit.org/stream, and so theoretically there would be some coherence to displaying a stack trace in the opposite order, but I think that's a bit of a red herring in this case and we'd be better off displaying stack traces in the same order everywhere.

**Comment by ohAitch** [comment]
+1 on flipping web stack trace order, having it be upside down has always
felt a bit weird

As for moves, I'm not sure what you mean by "monolithic construction": when
I think of a list that has multiple moves, it's currently going to get
constructed as

++  foo
  =.  mow  :_(mow [%poke foo])
  =.  +>  bar-changing-mow
  =.  mow (weld (diffs-for /baz) mow)

with things being pushed to the end of the requested traversal.

It's true that it's /read/ monolithically by gall/arvo, but that's a
question of one piece of os-level code vs all usage of the API in userspace

**Comment by cgyarvin** [comment]
With move lists, the situation is: lots of pieces of user code construct
them; one piece of system code traverses them.  So they should be optimized
for easy construction.  The real issue is that producing lists in reverse
order is slightly counterintuitive.  But my usual bias is that people can
learn.

I do think stacks should be printed with the top of the stack at the bottom
of the screen.  This is just a bug.

**Comment by belisarius222** [comment]
Ok, I'm sold on reversing move lists. That seems like something that should
be done in one system-wide pull request, and probably also at the arvo/vere
interface, I'd imagine.

**Comment by ohAitch** [comment]
They're already reverse system wide?

**Comment by cgyarvin** [comment]
I think there are some places where they don’t get flopped at at all the right time...

**Comment by jtobin** [comment]
Going to close this as I think whether or not there's actually an issue is no longer clear.
