### ISSUE TITLE
Clay & Eyre features in the coming release

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#934]
With so much work happening it has been hard to keep track of what is going to make it into 
the coming release, so let me ask the pertinent question: are the long awaited fix for Clay (large file history) and routing capabilities for Eyre (perhaps coming in `light`? CC @eglaysher) hanging somewhere out there?

@galenwp will be interested in this, because these two things are essentially what has been holding release of `urbit-elm` for quite a few months already. Perhaps we could wait some more with routing in the webserver, but clay blowup on "large" (read ~1M) files makes it totally impossible to distribute any reasonably complex app, including plato itself, without risking spontaneous combustion of user ships.

**Comment by joemfb** [comment]
Hi @mikolajpp, 

A lot has changed since you first ran into the issue of stack overflows on %clay syncs. My suspicious is that it was the at-the-time absence of tail-call-optimization in the Hoon AES CTR mode implementation (unjetted). But there have also been rewrites of the `+jam` jet (adding an explicit stack, won't overflow) and the nock bytecode interpreter (likewise).

The current `%/web/landscape/js/index/js` bundle is 3.4 MB -- while that is unfortunate and it will be shrunk, we've been able to use it and update/sync it on internal testnets.

It's also easier to boot fake-key ships and test local networks. The `-F` CLI arg takes any ship smaller than a comet:

```
urbit -F ~zod -A ./arvo -s -c fake-zod
urbit -F ~marzod -A ./arvo -s -c fake-marzod
urbit -F ~wicdev-wisryt -A ./arvo -s -c fake-wicdev-wisryt
...
```

Local-networking with fake ships no longer cheats by sending huge packets, so this would actually be a legitimate test.

**Comment by mikolajpp** [comment]
That sounds promising @joemfb. I will try to do some testing over the weekend and report here. If this  thing works, then the only thing left would be client-side routing in our webserver, but I guess that will take some time until @eglaysher has `light:` working.

**Comment by jtobin** [comment]
Closing as this question has been resolved.
